name: Release

on:
  release:
    types: [published]

jobs:
  Build_And_Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -ldflags="-w -s"  -o ghproxy .

      - name: Create Release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ghproxy application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
